#!/usr/bin/env node
// zoom-out installer.
//
// One source of truth — hooks/reflex.txt (the reflex) and skills/zoom-out/
// (the full protocol) — rendered into each coding agent's documented discovery
// surface. Nothing here is hand-maintained per agent: adding an agent is a row
// in AGENTS, not new code, so the surface set cannot silently drift away from
// the skill.
//
// Two kinds of surface, because agents differ in what they guarantee:
//
//   skill  — a SKILL.md directory the agent discovers and loads on relevance.
//            Portable across the Agent Skills standard (agentskills.io), but
//            trigger-dependent: the agent must decide the skill is relevant.
//   rules  — an always-on instruction file the agent injects into every
//            session regardless of triggering. This is where the reflex is
//            guaranteed rather than hoped for, on agents with no hook API.
//
// Usage:
//   node scripts/install.mjs [options]
//
//   --scope user|project|all   Which scopes to install (default: all)
//   --agents <ids|all>         Comma-separated agent ids, or all (default:
//                              detected agents plus the portable standard)
//   --home <dir>               Home directory to install into (default: $HOME)
//   --root <dir>               Project root (default: cwd)
//   --list                     Show the surface matrix and exit
//   --matrix                   Print the README compatibility matrix and exit
//   --dry-run                  Print planned writes without touching disk
//   --uninstall                Remove what this script installed
//   --force                    Overwrite unmanaged rule files
"use strict";

import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SELF_DIR = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(SELF_DIR, "..");
const SKILL_NAME = "zoom-out";
const SKILL_SRC = join(REPO, "skills", SKILL_NAME);
const REFLEX = readFileSync(join(REPO, "hooks", "reflex.txt"), "utf8").trim();

const SKILL_POINTER =
  "Full protocol: the `zoom-out` skill (SKILL.md) installed alongside this file.";

const BEGIN = "<!-- zoom-out:begin (managed by scripts/install.mjs) -->";
const END = "<!-- zoom-out:end -->";
const GENERATED = "<!-- generated by zoom-out (scripts/install.mjs) -->";
const GENERATED_YAML = "generated-by: zoom-out";

// ---------------------------------------------------------------------------
// Surfaces
//
// `share` is the at-work adoption figure from the JetBrains Developer
// Ecosystem Survey 2026 (n=15,509, May–July 2026) unless noted. Paths are
// literal: a leading ~/ is the user's home, anything else is relative to the
// project root. Every entry cites the doc it was verified against.
// ---------------------------------------------------------------------------

export const AGENTS = [
  {
    id: "claude-code",
    label: "Claude Code",
    share: "39%",
    detect: ["~/.claude"],
    skills: { user: ["~/.claude/skills"], project: [".claude/skills"] },
    rules: [],
    injection:
      "SessionStart hook (hooks/hooks.json) — shipped, installed with the plugin",
    notes:
      "Does not read .agents/skills. Personal skills come from ~/.claude/skills, project skills from .claude/skills, and any skill directory may be a symlink.",
    sources: ["https://code.claude.com/docs/en/skills"],
  },
  {
    id: "codex",
    label: "Codex (OpenAI)",
    share: "16%",
    detect: ["~/.codex"],
    skills: {
      user: ["~/.agents/skills", "~/.codex/skills"],
      project: [".agents/skills", ".codex/skills"],
    },
    rules: [
      { scope: "user", path: "~/.codex/AGENTS.md", kind: "block" },
      { scope: "project", path: "AGENTS.md", kind: "block" },
    ],
    injection: "AGENTS.md (plain markdown, no frontmatter needed)",
    notes:
      "Repo skills are read from .agents/skills in the cwd, every parent up to the repo root, then ~/.agents/skills and /etc/codex/skills. ~/.codex/skills and <repo>/.codex/skills are live but deprecated in Codex's source, and absent from its docs table. AGENTS.override.md beats AGENTS.md wherever it exists.",
    sources: [
      "https://learn.chatgpt.com/docs/build-skills",
      "https://learn.chatgpt.com/docs/agent-configuration/agents-md",
    ],
  },
  {
    id: "copilot",
    label: "GitHub Copilot (VS Code, CLI, cloud agent)",
    share: "21%",
    detect: ["~/.copilot"],
    skills: {
      user: ["~/.agents/skills", "~/.copilot/skills"],
      project: [".agents/skills", ".github/skills"],
    },
    rules: [
      {
        scope: "project",
        path: ".github/instructions/zoom-out.instructions.md",
        kind: "file",
        frontmatter: {
          description:
            "Zoom-out reflex: before calling a fix, diagnosis, or plan complete, ask whether it is one instance of something bigger.",
          applyTo: "**",
        },
      },
      { scope: "project", path: ".github/copilot-instructions.md", kind: "block" },
    ],
    injection:
      ".github/instructions/*.instructions.md with applyTo: '**', plus the repo-wide .github/copilot-instructions.md",
    notes:
      "Project skills: .github/skills, .claude/skills, .agents/skills. Personal skills: ~/.copilot/skills, ~/.claude/skills, ~/.agents/skills. Both instruction files are written because the cloud agent and code review read the repo-wide file, while VS Code and the CLI honour applyTo.",
    sources: [
      "https://docs.github.com/en/copilot/concepts/agents/about-agent-skills",
      "https://code.visualstudio.com/docs/agent-customization/agent-skills",
      "https://code.visualstudio.com/docs/agent-customization/custom-instructions",
    ],
  },
  {
    id: "cursor",
    label: "Cursor",
    share: "12%",
    detect: ["~/.cursor"],
    skills: {
      user: ["~/.agents/skills", "~/.cursor/skills"],
      project: [".agents/skills", ".cursor/skills"],
    },
    rules: [
      {
        scope: "project",
        path: ".cursor/rules/zoom-out.mdc",
        kind: "file",
        frontmatter: {
          description:
            "Zoom-out reflex: before calling a fix, diagnosis, or plan complete, ask whether it is one instance of something bigger.",
          alwaysApply: true,
        },
      },
    ],
    injection: ".cursor/rules/*.mdc with alwaysApply: true",
    notes:
      "Only .mdc files in .cursor/rules are read; a plain .md there is ignored. Also loads .claude/skills, .codex/skills, ~/.claude/skills, ~/.codex/skills for compatibility. Mirrored copies are kept on purpose: Cursor has had injection-stage bugs where an aliased skill appeared in menus but never reached the prompt.",
    sources: ["https://cursor.com/docs/skills", "https://cursor.com/docs/rules"],
  },
  {
    id: "gemini-cli",
    label: "Gemini CLI",
    share: "6%",
    detect: ["~/.gemini"],
    skills: {
      user: ["~/.agents/skills", "~/.gemini/skills"],
      project: [".agents/skills", ".gemini/skills"],
    },
    rules: [
      { scope: "user", path: "~/.gemini/GEMINI.md", kind: "block" },
      { scope: "project", path: "GEMINI.md", kind: "block" },
    ],
    injection: "GEMINI.md (whole file sent with every prompt)",
    notes:
      "The .agents/skills alias takes precedence over .gemini/skills within the same tier. AGENTS.md is not read by default — the filename list is configurable through context.fileName. Replaced by Antigravity CLI for unpaid and Google One tiers on 2026-06-18; enterprise access is unchanged.",
    sources: ["https://geminicli.com/docs/cli/skills", "https://geminicli.com/docs/cli/gemini-md"],
  },
  {
    id: "antigravity",
    label: "Google Antigravity (2.0 / CLI / IDE)",
    share: "6%",
    detect: ["~/.gemini"],
    skills: {
      user: ["~/.gemini/config/skills", "~/.gemini/antigravity-cli/skills"],
      project: [".agents/skills"],
    },
    rules: [
      { scope: "user", path: "~/.gemini/GEMINI.md", kind: "block" },
      { scope: "project", path: "AGENTS.md", kind: "block" },
      { scope: "project", path: ".agents/rules/zoom-out.md", kind: "file" },
    ],
    injection:
      "GEMINI.md and root AGENTS.md (parsed at startup); .agents/rules for the rules engine",
    notes:
      "Skills live in .agents/skills (legacy .agent/skills still read); CLI user skills are ~/.gemini/antigravity-cli/skills, 2.0 and IDE use ~/.gemini/config/skills. The per-rule frontmatter key for the 'Always on' activation mode is undocumented, so the always-on guarantee comes from GEMINI.md/AGENTS.md; .agents/rules is written as the documented IDE/2.0 rule location.",
    sources: [
      "https://antigravity.google/docs/skills",
      "https://antigravity.google/docs/rules-workflows",
      "https://antigravity.google/docs/cli/best-practices",
    ],
  },
  {
    id: "opencode",
    label: "OpenCode",
    share: "7%",
    detect: ["~/.config/opencode"],
    skills: {
      user: ["~/.agents/skills", "~/.config/opencode/skills"],
      project: [".agents/skills", ".opencode/skills"],
    },
    rules: [
      { scope: "user", path: "~/.config/opencode/AGENTS.md", kind: "block" },
      { scope: "project", path: "AGENTS.md", kind: "block" },
    ],
    injection: "AGENTS.md (plain markdown, no frontmatter needed)",
    notes:
      "Walks up to the git worktree root loading .opencode/skills, .claude/skills and .agents/skills along the way. No documented session-start context hook.",
    sources: ["https://opencode.ai/docs/skills", "https://opencode.ai/docs/rules"],
  },
  {
    id: "junie",
    label: "JetBrains Junie",
    share: "9%",
    detect: ["~/.junie"],
    skills: {
      user: ["~/.agents/skills", "~/.junie/skills"],
      project: [".agents/skills", ".junie/skills"],
    },
    rules: [{ scope: "user", path: "~/.junie/AGENTS.md", kind: "block" }],
    injection: "AGENTS.md — the project root file, plus ~/.junie/AGENTS.md globally",
    notes:
      "Project guidelines come from .junie/AGENTS.md if it exists (used exclusively), otherwise the root AGENTS.md combined with .junie/playbook.md and .junie/rules/*.md. This installer writes the root file and the global one, and never creates .junie/AGENTS.md, which would shadow the root file for Junie alone. Also detects .cursor/skills, .claude/skills and .codex/skills and offers to import them.",
    sources: [
      "https://junie.jetbrains.com/docs/agent-skills.html",
      "https://junie.jetbrains.com/docs/guidelines-and-memory.html",
    ],
  },
  {
    id: "kiro",
    label: "AWS Kiro",
    share: "—",
    detect: ["~/.kiro"],
    skills: { user: ["~/.kiro/skills"], project: [".kiro/skills"] },
    rules: [
      {
        scope: "user",
        path: "~/.kiro/steering/zoom-out.md",
        kind: "file",
        frontmatter: { inclusion: "always" },
      },
      {
        scope: "project",
        path: ".kiro/steering/zoom-out.md",
        kind: "file",
        frontmatter: { inclusion: "always" },
      },
    ],
    injection: ".kiro/steering/*.md with inclusion: always",
    notes:
      "The only agent here that does not read .agents/skills. Steering frontmatter must be the first content in the file. Root and nested AGENTS.md are also always included. Custom agents do not inherit steering or skills unless the paths are listed in their resources.",
    sources: ["https://kiro.dev/docs/skills", "https://kiro.dev/docs/steering"],
  },
  {
    id: "cline",
    label: "Cline",
    share: "—",
    detect: ["~/.cline"],
    skills: {
      user: ["~/.cline/skills"],
      project: [".cline/skills", ".claude/skills"],
    },
    rules: [
      { scope: "user", path: "~/.agents/AGENTS.md", kind: "block" },
      { scope: "project", path: ".clinerules/zoom-out.md", kind: "file" },
    ],
    injection: ".clinerules/ (rules without frontmatter are always active)",
    notes:
      "Reads .cline/skills, .clinerules/skills and .claude/skills, but not .agents/skills. Global rules live in ~/Documents/Cline/Rules, ~/.cline/rules and ~/Cline/Rules; the cross-tool global file it reads is ~/.agents/AGENTS.md. Also auto-detects AGENTS.md, .cursorrules and .windsurfrules. Conditional rules use a paths: frontmatter key — this file deliberately has none.",
    sources: ["https://docs.cline.bot/customization/cline-rules", "https://docs.cline.bot/customization/skills"],
  },
  {
    id: "roo-code",
    label: "Roo Code",
    share: "—",
    detect: ["~/.roo"],
    skills: {
      user: ["~/.agents/skills", "~/.roo/skills"],
      project: [".agents/skills", ".roo/skills"],
    },
    rules: [
      { scope: "user", path: "~/.roo/rules/zoom-out.md", kind: "file" },
      { scope: "project", path: ".roo/rules/zoom-out.md", kind: "file" },
    ],
    injection: ".roo/rules/ (directory contents are appended to the system prompt)",
    notes:
      "Rules directories are read recursively in alphabetical order, so the filename decides its place. Also loads a workspace-root AGENTS.md unless roo-cline.useAgentRules is false. No documented session-start hook.",
    sources: ["https://docs.roocode.com/features/custom-instructions", "https://docs.roocode.com/features/skills"],
  },
  {
    id: "devin",
    label: "Devin Desktop / Windsurf, Devin CLI",
    share: "—",
    detect: ["~/.codeium", "~/.config/devin"],
    skills: {
      user: ["~/.config/devin/skills", "~/.codeium/windsurf/skills"],
      project: [".devin/skills", ".windsurf/skills"],
    },
    rules: [
      {
        scope: "user",
        path: "~/.codeium/windsurf/memories/global_rules.md",
        kind: "block",
      },
      {
        scope: "project",
        path: ".devin/rules/zoom-out.md",
        kind: "file",
        frontmatter: { trigger: "always_on" },
      },
    ],
    injection: ".devin/rules/*.md with trigger: always_on (legacy .windsurf/rules)",
    notes:
      "Root AGENTS.md is always on; subdirectory AGENTS.md files are glob-scoped to their directory. The global rules file is capped at 6,000 characters and workspace rule files at 12,000. Windsurf was renamed Devin Desktop on 2026-06-02; .devin/ is preferred and .windsurf/ kept as the fallback.",
    sources: [
      "https://docs.devin.ai/desktop/cascade/memories",
      "https://docs.devin.ai/desktop/cascade/skills",
    ],
  },
  {
    id: "zed",
    label: "Zed",
    share: "—",
    detect: ["~/.config/zed"],
    skills: { user: ["~/.agents/skills"], project: [".agents/skills"] },
    rules: [{ scope: "user", path: "~/.config/zed/AGENTS.md", kind: "block" }],
    injection: "AGENTS.md (personal ~/.config/zed/AGENTS.md, project root)",
    notes:
      "For project instructions Zed uses the first file that exists in this order: .rules, .cursorrules, .windsurfrules, .clinerules, .github/copilot-instructions.md, AGENT.md, AGENTS.md, CLAUDE.md, GEMINI.md — so an existing .rules wins over the AGENTS.md block.",
    sources: ["https://zed.dev/docs/ai/instructions", "https://zed.dev/docs/ai/skills"],
  },
  {
    id: "amp",
    label: "Amp",
    share: "—",
    detect: ["~/.config/amp"],
    skills: {
      user: ["~/.agents/skills", "~/.config/amp/skills"],
      project: [".agents/skills"],
    },
    rules: [{ scope: "user", path: "~/.config/amp/AGENTS.md", kind: "block" }],
    injection: "AGENTS.md (cwd, parents up to $HOME, and ~/.config/amp/AGENTS.md)",
    notes:
      "AGENTS.md in the cwd and every parent up to $HOME is always included, as are $HOME/.config/amp/AGENTS.md and $HOME/.config/AGENTS.md. AGENT.md or CLAUDE.md is used only when no AGENTS.md exists in that directory. No documented hook surface.",
    sources: ["https://ampcode.com/manual"],
  },
  {
    id: "goose",
    label: "Goose",
    share: "—",
    detect: ["~/.config/goose"],
    skills: { user: ["~/.agents/skills"], project: [".agents/skills"] },
    rules: [{ scope: "user", path: "~/.config/goose/.goosehints", kind: "block" }],
    injection: "AGENTS.md and .goosehints, added to the system prompt for every request",
    notes:
      "Goose looks for AGENTS.md and .goosehints at each level from the cwd up to the repo root; local hints win over global. Its SessionStart hook is observation-only — no documented context injection.",
    sources: ["https://goose-docs.ai/docs/guides/context-engineering/using-goosehints"],
  },
  {
    id: "ona",
    label: "Ona",
    share: "—",
    detect: [],
    skills: {
      user: [],
      project: [".agents/skills", ".ona/skills"],
    },
    rules: [{ scope: "project", path: "AGENTS.md", kind: "block" }],
    injection: "AGENTS.md, loaded at the start of every session",
    notes:
      "Repository skills win over organization skills, which win over built-in ones. No documented session-start hook.",
    sources: ["https://ona.com/docs/ona/agents-md", "https://ona.com/docs/ona/agents/skills"],
  },
  {
    id: "pi",
    label: "pi",
    share: "—",
    detect: ["~/.pi"],
    skills: { user: [], project: [] },
    rules: [],
    injection: "hooks/zoom-out-reflex.ts (before_agent_start) — shipped",
    notes:
      "Installed as a package (`pi install git:...`); skills come from the package's skills/ directory.",
    sources: [
      "https://github.com/badlogic/pi-mono/blob/main/packages/coding-agent/docs/skills.md",
    ],
  },
  {
    id: "omp",
    label: "omp / oh-my-pi",
    share: "—",
    detect: ["~/.omp"],
    skills: { user: ["~/.omp/agent/skills"], project: [] },
    rules: [],
    injection: "hooks/zoom-out-reflex.ts (before_agent_start) — shipped",
    notes:
      "Installed as a Claude-compatible plugin from .claude-plugin/marketplace.json; also reads ~/.omp/agent/skills/.",
    sources: ["https://agentskills.io/clients"],
  },
];

// Agents every standard-conformant tool reads. Kept separate from the named
// agents because these paths are the standard, not a vendor convention.
export const STANDARD = {
  id: "agents-standard",
  label: "Agent Skills / AGENTS.md standard",
  share: "—",
  skills: { user: ["~/.agents/skills"], project: [".agents/skills"] },
  rules: [{ scope: "project", path: "AGENTS.md", kind: "block" }],
  injection: "AGENTS.md block",
  notes:
    "The portable roots: any agent implementing the Agent Skills standard or the AGENTS.md format picks these up. Always installed.",
  sources: ["https://agentskills.io/specification", "https://agents.md/"],
};

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

function reflexBlock(indent) {
  return REFLEX.split("\n")
    .map((line) => (indent && line ? indent + line : line))
    .join("\n");
}

// Body of an always-on rule: the reflex verbatim, plus where to find the full
// protocol. Generated, never hand-edited.
function rulesBody() {
  return `${reflexBlock("")}

${SKILL_POINTER}`;
}

function frontmatterYaml(meta) {
  const lines = [GENERATED_YAML];
  for (const [key, value] of Object.entries(meta || {})) {
    lines.push(`${key}: ${JSON.stringify(value)}`);
  }
  return lines.join("\n");
}

function renderRuleFile(entry) {
  const header = entry.frontmatter
    ? `---\n${frontmatterYaml(entry.frontmatter)}\n---\n\n`
    : "";
  return `${header}${GENERATED}\n\n${rulesBody()}\n`;
}

// A file belongs to this installer only if it carries the generated marker.
// Everything else is someone's hand-written rule and is left alone.
function isGenerated(content) {
  return (
    content.startsWith(`---\n${GENERATED_YAML}`) || content.startsWith(GENERATED)
  );
}

function escapeRe(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// Append or replace the managed block inside a shared file (AGENTS.md,
// GEMINI.md, ...). Everything outside the markers is preserved.
function upsertBlock(existing, body) {
  const block = `${BEGIN}\n${body}\n${END}`;
  const pattern = new RegExp(`${escapeRe(BEGIN)}[\\s\\S]*?${escapeRe(END)}`);
  if (pattern.test(existing)) return existing.replace(pattern, block);
  const trimmed = existing.trimEnd();
  return trimmed === "" ? `${block}\n` : `${trimmed}\n\n${block}\n`;
}

function stripBlock(existing) {
  const pattern = new RegExp(`\\n*${escapeRe(BEGIN)}[\\s\\S]*?${escapeRe(END)}\\n*`);
  return pattern.test(existing) ? existing.replace(pattern, "\n") : null;
}

// ---------------------------------------------------------------------------
// Paths and planning
// ---------------------------------------------------------------------------

function expand(path, { home, root, scope }) {
  if (path.startsWith("~/")) return join(home, path.slice(2));
  return join(scope === "user" ? home : root, path);
}

function planFor(agent, { scopes, home, root }) {
  const plan = [];
  for (const scope of scopes) {
    const roots = agent.skills?.[scope] ?? [];
    for (const raw of new Set(roots)) {
      const dest = join(expand(raw, { home, root, scope }), SKILL_NAME);
      plan.push({ kind: "skill", agent, scope, raw, dest });
    }
    for (const rule of (agent.rules || []).filter((r) => r.scope === scope)) {
      const dest = expand(rule.path, { home, root, scope });
      plan.push({ kind: "rule", agent, scope, rule, raw: rule.path, dest });
    }
  }
  return plan;
}

function detectHomeAgents(home) {
  const detected = new Set();
  for (const agent of AGENTS) {
    if (!agent.detect) continue;
    if (agent.detect.some((d) => existsSync(join(home, d.replace(/^~\//, ""))))) {
      detected.add(agent.id);
    }
  }
  return detected;
}

// ---------------------------------------------------------------------------
// Apply
// ---------------------------------------------------------------------------

function installItem(item, ctx) {
  return item.kind === "skill" ? installSkill(item, ctx) : installRule(item, ctx);
}

function installSkill(item, ctx) {
  const { dryRun } = ctx;
  if (dryRun)
    return [`skill  ${item.raw.replace(/\/$/, "")}/${SKILL_NAME}/  <- skills/${SKILL_NAME}/`];
  mkdirSync(dirname(item.dest), { recursive: true });
  cpSync(SKILL_SRC, item.dest, { recursive: true });
  return [`skill  ${item.dest}`];
}

function installRule(item, ctx) {
  const { dryRun, force } = ctx;
  if (item.rule.kind === "file") {
    if (existsSync(item.dest) && !force) {
      const current = readFileSync(item.dest, "utf8");
      if (!isGenerated(current)) {
        return [`SKIP   ${item.dest} (exists, not generated; --force to overwrite)`];
      }
    }
    if (dryRun) return [`rule   ${item.rule.path}`];
    mkdirSync(dirname(item.dest), { recursive: true });
    writeFileSync(item.dest, renderRuleFile(item.rule));
    return [`rule   ${item.dest}`];
  }
  const existing = existsSync(item.dest) ? readFileSync(item.dest, "utf8") : "";
  if (dryRun) return [`rule   ${item.raw} (managed block)`];
  mkdirSync(dirname(item.dest), { recursive: true });
  writeFileSync(item.dest, upsertBlock(existing, rulesBody()));
  return [`rule   ${item.dest} (managed block)`];
}

function uninstallItem(item, ctx) {
  const { dryRun } = ctx;
  if (!existsSync(item.dest)) return [];
  if (item.kind === "skill") {
    if (dryRun) return [`skill  -${item.dest}`];
    rmSync(item.dest, { recursive: true, force: true });
    return [`skill  -${item.dest}`];
  }
  if (item.rule.kind === "file") {
    const current = readFileSync(item.dest, "utf8");
    if (!isGenerated(current)) {
      return [`SKIP   ${item.dest} (not generated; left alone)`];
    }
    if (dryRun) return [`rule   -${item.dest}`];
    rmSync(item.dest);
    return [`rule   -${item.dest}`];
  }
  const stripped = stripBlock(readFileSync(item.dest, "utf8"));
  if (stripped === null) return [];
  // A file that held nothing but the managed block was created by this
  // installer; leaving an empty file behind would be litter, not safety.
  if (stripped.trim() === "") {
    if (dryRun) return [`rule   -${item.raw} (file emptied, removed)`];
    rmSync(item.dest);
    return [`rule   -${item.dest} (file emptied, removed)`];
  }
  if (dryRun) return [`rule   -${item.raw} (managed block)`];
  writeFileSync(item.dest, stripped.replace(/^\n+/, ""));
  return [`rule   -${item.dest} (managed block)`];
}

// ---------------------------------------------------------------------------
// Output
// ---------------------------------------------------------------------------

function selectedAgents({ agents, home, scope }) {
  const pool = [...AGENTS, STANDARD];
  if (agents === "all") return pool;
  const wanted = new Set(agents.split(",").map((s) => s.trim()).filter(Boolean));
  const detected = detectHomeAgents(home);
  return pool.filter((a) => wanted.has(a.id) || (wanted.size === 0 && (detected.has(a.id) || a.id === STANDARD.id)));
}

function printList(agents, { home, scope }) {
  const detected = detectHomeAgents(home);
  console.log("zoom-out surfaces\n");
  for (const a of [...AGENTS, STANDARD]) {
    const state = agents.includes(a) ? "selected" : detected.has(a.id) ? "available" : "-";
    const skills = [...(a.skills?.user ?? []), ...(a.skills?.project ?? [])];
    console.log(`${a.id.padEnd(16)} ${a.share.padEnd(5)} ${state.padEnd(10)} ${a.injection}`);
    for (const s of skills) console.log(`${" ".repeat(16)} skill  ${s}/${SKILL_NAME}/`);
    for (const r of a.rules ?? []) console.log(`${" ".repeat(16)} rule   ${r.scope}: ${r.path}`);
  }
  console.log("\n--agents all | --agents <id,...> to widen; --scope user|project|all");
}

function printMatrix() {
  const rows = [
    "| Agent | At-work share | Skill discovery root | Always-on surface |",
    "| --- | --- | --- | --- |",
  ];
  for (const a of [...AGENTS, STANDARD]) {
    const roots = [...(a.skills?.user ?? []), ...(a.skills?.project ?? [])];
    const rules = (a.rules ?? []).map((r) => r.path).join(", ") || a.injection;
    rows.push(
      `| ${a.label} | ${a.share} | ${roots.length ? roots.map((r) => `${r}/zoom-out/`).join(", ") : "—"} | ${rules} |`
    );
  }
  console.log(rows.join("\n"));
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

function parseArgs(argv) {
  const opts = {
    scope: "all",
    agents: "",
    home: homedir(),
    root: process.cwd(),
    dryRun: false,
    force: false,
    uninstall: false,
    list: false,
    matrix: false,
  };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    const next = () => {
      const value = argv[++i];
      if (value === undefined) throw new Error(`${arg} needs a value`);
      return value;
    };
    switch (arg) {
      case "--scope": opts.scope = next(); break;
      case "--agents": opts.agents = next(); break;
      case "--home": opts.home = resolve(next()); break;
      case "--root": opts.root = resolve(next()); break;
      case "--dry-run": opts.dryRun = true; break;
      case "--force": opts.force = true; break;
      case "--uninstall": opts.uninstall = true; break;
      case "--list": opts.list = true; break;
      case "--matrix": opts.matrix = true; break;
      case "-h":
      case "--help": opts.help = true; break;
      default: throw new Error(`unknown option ${arg}`);
    }
  }
  return opts;
}

function main(argv) {
  const opts = parseArgs(argv);
  if (opts.help) {
    console.log(readFileSync(new URL(import.meta.url), "utf8").split("\n").slice(1, 30).map((l) => l.replace(/^\/\/ ?/, "")).join("\n"));
    return 0;
  }
  if (opts.matrix) {
    printMatrix();
    return 0;
  }
  const scopes = opts.scope === "all" ? ["user", "project"] : [opts.scope];
  if (!scopes.every((s) => s === "user" || s === "project")) {
    throw new Error(`--scope must be user, project, or all (got ${opts.scope})`);
  }
  const agents = selectedAgents({ agents: opts.agents, home: opts.home, scope: scopes });
  if (opts.list) {
    printList(agents, { home: opts.home, scope: scopes });
    return 0;
  }

  // Several agents share a surface (AGENTS.md, ~/.agents/skills); write each
  // destination once, whatever the number of agents that read it.
  const seen = new Set();
  const items = agents
    .flatMap((a) => planFor(a, { scopes, home: opts.home, root: opts.root }))
    .filter((item) => {
      const key = `${item.kind}:${item.dest}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    });
  const ctx = { ...opts };
  const verb = opts.uninstall ? "uninstall" : "install";
  console.log(
    `zoom-out ${verb}${opts.dryRun ? " (dry run)" : ""} — ${items.length} surface(s), ` +
      `home=${opts.home} root=${opts.root}`
  );
  if (items.length === 0) {
    console.log("nothing selected; use --agents all");
    return 0;
  }
  for (const item of items) {
    const lines = opts.uninstall ? uninstallItem(item, ctx) : installItem(item, ctx);
    for (const line of lines) console.log("  " + line);
  }
  if (!opts.dryRun) {
    console.log(
      opts.uninstall
        ? "\nRemoved. Restart any running agent session to pick up the change."
        : "\nDone. Restart any running agent session so it re-reads its instruction files."
    );
  }
  return 0;
}

try {
  const invokedDirectly =
    process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
  if (invokedDirectly) process.exit(main(process.argv.slice(2)));
} catch (error) {
  console.error(`zoom-out: ${error.message}`);
  process.exit(1);
}